
services:
  main-applic:
    build:
      context: main-applic
      dockerfile: Dockerfile
    container_name: main-applic_container
    ports:
      - "127.0.0.1:3006:3006"
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure
    environment:
      TZ: "Europe/Moscow"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:3006/api/healthcheck"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 10s
    volumes:
      - ./main-applic/public/temporary:/app/public/temporary
      - ./main-applic/prisma:/app/prisma

  nginx:
    image: nginx:1.27.5-alpine
    container_name: nginx_container
    ports:
      - "80:80"
    volumes:
      - ./main-applic/public/temporary:/opt/files
      - ./log/report:/opt/report
      - ./.htpasswd:/opt/.htpasswd
      - ./nginx_config/nginx.conf:/etc/nginx/nginx.conf
      - ./log/nginx:/var/log/nginx
    environment:
      TZ: Europe/Moscow
    depends_on:
      main-applic:
        condition: service_healthy
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "--silent", "--fail", "http://localhost:80/health"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 10s

  # db_sqlite:
  #   container_name: db_sqlite_container
  #   image: nouchka/sqlite3
  #   volumes:
  #     - /opt/iul-now-June-25/main-applic/prisma:/database
  #   tty: true
  #   stdin_open: true
  #   working_dir: /database
  #   entrypoint: >
  #     sh -c "
  #     if [ ! -f /database/database-sql-lite.db ]; then
  #       echo 'Создаём базу данных...';
  #       sqlite3 /database/database-sql-lite.db 'PRAGMA journal_mode=WAL;';
  #     fi;
  #     exec sqlite3 /database/database-sql-lite.db
  #     "
  #   healthcheck:
  #     test: ["CMD-SHELL", "sqlite3 /database/database-sql-lite.db 'SELECT 1;'"]
  #     interval: 5s
  #     timeout: 3s
  #     retries: 5
  #     start_period: 10s

  postgres:
    build:
      context: postgres-db
      dockerfile: Dockerfile
    container_name: db_postgres_container
    volumes:
      - database_volume:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    env_file:
      - ./main-applic/.env
    environment:
      TZ: "Europe/Moscow"
      POSTGRES_DB: "${NEXT_PUBLIC_DB_NAME_DEV}"
      POSTGRES_USER: "${NEXT_PUBLIC_DB_USER_DEV}"
      POSTGRES_PASSWORD: "${NEXT_PUBLIC_DB_PASSWORD_DEV}"
      PGDATA: "/var/lib/postgresql/data" # можно не указывать, если используете дефолт
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${NEXT_PUBLIC_DB_USER_DEV} -d ${NEXT_PUBLIC_DB_NAME_DEV}"
        ]
      interval: 5s
      timeout: 3s
      retries: 2
      start_period: 5s

volumes:
  database_volume:
