/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import java.io.PrintStream

// class App {
//     val greeting: String
//         get() {
//             return "Приве!"
//         }
// }

fun main() {
    // Для записи в консоль
    // System.out.print("Привет, мир!\n")

    // Или явно через PrintStream с UTF-8
    val out = PrintStream(System.out, true, "UTF-8")
    out.println("Привет, мир!")
}
